import { sampleStories } from "./sample-stories.js";
import { config } from "./config.js";
import path from "node:path";
import { searchLinkup, generateOpenAI, findElevenLabsVoice, createSpeech, publishTelegram, publishTelegramAudio } from "./integrations.js";
import { sourceDiversity } from "./news.js";
const stop=new Set(["the","a","an","of","to","and","in","for","on","with","after"]);
function words(s){return new Set(String(s||"").toLowerCase().replace(/[^a-z0-9 ]/g," ").split(/\s+/).filter(x=>x.length>3&&!stop.has(x)));}
function overlap(a,b){const x=words(a),y=words(b);return [...x].filter(v=>y.has(v)).length;}
export async function monitor(){const raw=!config.demoMode&&config.linkupKey?await searchLinkup(config.linkupKey):sampleStories;const stories=raw.map((s,i)=>({...s,id:`story-${i+1}`,relevance:Math.max(20,100-i*3)}));stories.sourceCount=sourceDiversity(stories);return stories;}
export async function editor(stories){const clean=stories.filter(s=>s.source!=="Social Media");if(!config.demoMode&&config.openaiKey){const result=await generateOpenAI(config.openaiKey,config.openaiModel,"You are the Editor agent. Return JSON with a rundown array containing exactly five source story objects, preserving title, source, url and summary. Rank by public importance, recency and category diversity. Never invent facts or URLs.",{stories:clean});return result.rundown.map((s,i)=>({...s,rank:i+1,angle:i===0?"Lead story":"News brief"}));}return clean.sort((a,b)=>b.relevance-a.relevance).slice(0,5).map((s,i)=>({...s,rank:i+1,angle:i===0?"Lead story":"News brief"}));}
export async function writer(rundown){if(!config.demoMode&&config.openaiKey)return generateOpenAI(config.openaiKey,config.openaiModel,"You are the Writer agent for an Indian audio newsroom. Return JSON: headline, script, citations. Write a concise 90-second broadcast using only supplied facts. citations must preserve each source URL and source name.",{rundown});const lines=rundown.map((s,i)=>`${i===0?"Our top story":"Also in the bulletin"}: ${s.title}. ${s.summary}`);return {headline:rundown[0].title,script:`Good morning. This is Overnight Newsroom. ${lines.join(" ")} That's your verified India briefing.`,citations:rundown.map(s=>({title:s.title,url:s.url,source:s.source}))};}
export async function judge(draft,rundown){const deterministic=()=>{const checks=draft.citations.map(c=>({claim:c.title,source:c.source,url:c.url,supported:rundown.some(s=>s.url===c.url||overlap(s.title,c.title)>=1)}));const passed=checks.every(c=>c.supported)&&draft.script.length>100;return {passed,checks,notes:passed?["All cited stories trace to selected sources."]:["One or more claims lack source support."]};};if(!config.demoMode&&config.openaiKey){const result=await generateOpenAI(config.openaiKey,config.openaiModel,"You are the independent Judge agent. Return JSON: passed boolean, checks array, notes array. Reject any claim not supported by supplied source material.",{draft,rundown});return result.passed?deterministic():result;}return deterministic();}
export async function anchor(draft,runId="bulletin"){if(!config.demoMode&&config.elevenLabsKey){const selected=config.elevenLabsVoiceId?{voice_id:config.elevenLabsVoiceId,name:"Configured voice"}:await findElevenLabsVoice(config.elevenLabsKey);const audioUrl=await createSpeech(config.elevenLabsKey,selected.voice_id,draft.script,runId);return {status:"generated",audioUrl,voiceId:selected.voice_id,voiceName:selected.name,durationSeconds:Math.ceil(draft.script.split(/\s+/).length/2.5)};}return {status:"demo",audioUrl:null,durationSeconds:Math.ceil(draft.script.split(/\s+/).length/2.5),message:"ElevenLabs is disabled in demo mode."};}
export async function publisher(draft,voice){let telegram=null,audioMessage=null;if(!config.demoMode&&config.telegramToken&&config.telegramChannel){telegram=await publishTelegram(config.telegramToken,config.telegramChannel,draft);if(voice.audioUrl)audioMessage=await publishTelegramAudio(config.telegramToken,config.telegramChannel,path.resolve("public",voice.audioUrl.replace(/^\//,"")),draft);}return {status:telegram?"published":"preview",channel:telegram?"telegram":"dashboard",telegramMessageId:telegram?.message_id,telegramAudioMessageId:audioMessage?.message_id,publishedAt:new Date().toISOString(),headline:draft.headline,text:draft.script,audioUrl:voice.audioUrl};}
export const agents={monitor,editor,writer,judge,anchor,publisher};
