const rows={
"Technology & AI":[["software-engineer","Software Engineer","developer backend cloud programming"],["ai-engineer","AI / ML Engineer","AI enthusiast machine learning LLM model coding"],["data-scientist","Data Scientist","analytics data statistics models"],["cybersecurity","Cybersecurity Professional","security CISO threat privacy"],["product-manager","Product Manager","product SaaS growth roadmap"],["cto","CTO / Technology Leader","technology enterprise cloud architecture"]],
"Healthcare & Life Sciences":[["doctor","Doctor / Physician","physician clinical medicine hospital healthcare"],["surgeon","Surgeon","surgery medical device hospital"],["pharma-professional","Pharma Professional","pharmaceutical drugs biotech regulation"],["healthcare-executive","Healthcare Executive","hospital policy insurance healthtech"],["medical-researcher","Medical Researcher","clinical trials science research biotech"]],
"Markets & Finance":[["investment-banker","Investment Banker","investment banking M&A deals capital markets"],["trader","Trader","trading markets stocks forex derivatives commodities"],["investor","Investor","investing equities portfolio valuation"],["hni","HNI / Family Office","wealth family office alternatives tax luxury"],["portfolio-manager","Portfolio Manager","asset management portfolio risk alpha"],["financial-advisor","Financial Advisor","wealth retirement mutual funds insurance"]],
"Business & Leadership":[["founder","Founder / Entrepreneur","startup founder funding competition growth"],["ceo","CEO / Business Leader","strategy enterprise policy leadership"],["consultant","Management Consultant","consulting strategy transformation industry"],["sales-leader","Sales Leader","sales revenue enterprise customers"],["marketer","Marketing Leader","brand advertising consumer growth"]],
"Law, Policy & Risk":[["lawyer","Lawyer / Legal Counsel","law courts regulation compliance"],["policy-professional","Policy Professional","government policy geopolitics regulation"],["risk-professional","Risk & Compliance Professional","risk compliance governance fraud"],["civil-servant","Civil Servant","government administration public policy"]],
"Industry & Operations":[["engineer","Engineer","engineering manufacturing infrastructure energy"],["real-estate","Real Estate Professional","property construction REIT housing"],["energy-professional","Energy Professional","oil gas renewables power climate"],["supply-chain","Supply Chain Leader","logistics manufacturing trade procurement"],["agri-professional","Agriculture Professional","agriculture food farming commodities"]],
"Research, Media & Education":[["researcher","Researcher / Academic","research university papers science"],["educator","Educator","education schools edtech learning"],["journalist","Journalist / Media Professional","media journalism politics culture"],["student","Student / Early Career","career jobs learning technology"]]
};
export const PERSONAS=Object.entries(rows).flatMap(([domain,list])=>list.map(([id,name,keywords])=>({id,name,domain,keywords:keywords.split(" ")})));
export const groupPersonas=list=>Object.groupBy(list,x=>x.domain);
export function searchPersonas(query=""){const terms=String(query).toLowerCase().trim().split(/\s+/).filter(Boolean);if(!terms.length)return PERSONAS;return PERSONAS.filter(p=>terms.every(t=>`${p.name} ${p.domain} ${p.keywords.join(" ")}`.toLowerCase().includes(t)));}
export function normalizeProfile(input={}){const personas=[...new Set(input.personas||[])].filter(id=>PERSONAS.some(p=>p.id===id));return {personas,primaryPersona:personas.includes(input.primaryPersona)?input.primaryPersona:personas[0]||"general",jobTitle:String(input.jobTitle||"").trim(),seniority:input.seniority||"individual-contributor",geographies:[...new Set(input.geographies||["India"])],watchlist:[...new Set((input.watchlist||[]).map(String).map(x=>x.trim()).filter(Boolean))],insightGoals:[...new Set(input.insightGoals||["impact"])]};}
export function rankStoriesForProfile(stories,profile={}){const p=normalizeProfile(profile),selected=PERSONAS.filter(x=>p.personas.includes(x.id)),watch=p.watchlist.map(x=>x.toLowerCase());return stories.map(story=>{const text=`${story.title} ${story.summary} ${story.category}`.toLowerCase(),terms=new Set(text.replace(/[^a-z0-9+.# ]/g," ").split(/\s+/).filter(Boolean));const has=term=>term.includes(" ")?text.includes(term):terms.has(term);const matched=selected.flatMap(x=>x.keywords).filter(has);const watched=watch.filter(has);const personaScore=matched.length*3+watched.length*7;return {...story,personaScore,whyForYou:watched.length?`Matches your watchlist: ${watched.join(", ")}`:matched.length?`Relevant to your ${selected[0]?.name||"professional"} persona`:`Broader context for your briefing`};}).sort((a,b)=>b.personaScore-a.personaScore);}
export const canManageNewsroom=role=>["admin","editor"].includes(role);
export const ROLE_OPTIONS=[{id:"user",name:"Member"},{id:"editor",name:"Analyst / Editor"},{id:"admin",name:"Administrator"}];
