const plans={
 doctor:{domains:["icmr.gov.in","cdsco.gov.in","who.int","thelancet.com","nejm.org","nature.com"],queries:["India medical clinical trials drug approvals and safety alerts last 7 days","new clinical guidelines disease surveillance hospital policy India last 7 days","peer reviewed medical and life sciences research practice changing last 7 days"]},
 "investment-banker":{domains:["nseindia.com","bseindia.com","sebi.gov.in","mca.gov.in","rbi.org.in","reuters.com"],queries:["India companies financial results earnings guidance and analyst calls last 7 days","India M&A fundraising IPO debt equity issuance corporate actions last 7 days","India company board management leadership role changes regulatory approvals last 7 days"]},
 trader:{domains:["nseindia.com","bseindia.com","sebi.gov.in","rbi.org.in","reuters.com"],queries:["India market moving earnings macro RBI SEBI flows and catalysts today","India listed company corporate actions guidance block deals insider trading today"]},
 investor:{domains:["nseindia.com","bseindia.com","sebi.gov.in","rbi.org.in","reuters.com"],queries:["India company earnings valuation drivers capital allocation and governance last 7 days","India sectors policy demand margin risks and long term opportunities last 7 days"]},
 "ai-engineer":{domains:["arxiv.org","github.com","huggingface.co","openai.com","anthropic.com","techcrunch.com"],queries:["AI model releases benchmarks papers security incidents and developer tools last 7 days","AI infrastructure chips cloud economics regulation and hiring last 7 days"]},
 engineer:{domains:["ieee.org","nature.com","reuters.com","pib.gov.in"],queries:["engineering infrastructure manufacturing energy standards and technology India last 7 days"]},
 founder:{domains:["reuters.com","techcrunch.com","inc42.com","yourstory.com","sebi.gov.in"],queries:["India startup funding acquisitions regulation competition and market shifts last 7 days"]}
};
const aliases={surgeon:"doctor","medical-researcher":"doctor","pharma-professional":"doctor","healthcare-executive":"doctor","portfolio-manager":"investor",hni:"investor","financial-advisor":"investor",cto:"ai-engineer","software-engineer":"ai-engineer","data-scientist":"ai-engineer",ceo:"founder"};
export function personaSearchPlan(personas=[],watchlist=[]){const selected=[...new Set(personas.map(x=>aliases[x]||x))],picked=selected.flatMap(x=>plans[x]?[plans[x]]:[]),watch=watchlist.filter(Boolean).join(" OR "),suffix=watch?` watchlist ${watch}`:"";return {queries:picked.flatMap((p,persona)=>p.queries.map(query=>({persona:selected[persona]||"professional",query:`${query}${suffix}`}))),domains:[...new Set(picked.flatMap(x=>x.domains))]};}
export const PROFESSIONAL_PLANS=plans;
