import http from "node:http";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { config } from "./config.js";
import { runPipeline } from "./pipeline.js";
import { listRuns } from "./store.js";
import { signup, createConnectToken, listUsers } from "./users.js";
import { convexSignup, latestBulletin, convexListUsers, convexSetUserRole, convexGetSetting, convexSetSetting, convexCreateWatchRule, convexUserWatchRules, convexAllWatchRules, convexSetWatchEnabled, convexRemoveWatchRule, convexRecentWatchAlerts, convexUserByEmail, convexUserById, convexUpdateUserProfile } from "./convex.js";
import { contentTypeFor } from "./server-utils.js";
import { PERSONAS, groupPersonas, rankStoriesForProfile, normalizeProfile, ROLE_OPTIONS } from "./personas.js";
import { personaSearchPlan } from "./persona-search.js";
import { searchLinkupPlan, generateOpenAI } from "./integrations.js";
import { attachProfessionalInsights, validateProfessionalInsights } from "./professional-insights.js";
import { normalizeWatchRule, TARGET_TYPES, EVENT_TYPES, URGENCY } from "./watch-rules.js";
import { verifyPassword,createAdminSession,verifyAdminSession,bearer } from "./admin-auth.js";
import { createUserSession,userFromRequest,hashUserPassword,verifyUserPassword } from "./user-auth.js";
import { buildFirstBriefing, sendTelegramBriefing } from "./first-briefing.js";
const json=(res,code,data)=>{res.writeHead(code,{"content-type":"application/json","access-control-allow-origin":"*"});res.end(JSON.stringify(data));};
const body=async req=>{let value="";for await(const chunk of req)value+=chunk;return JSON.parse(value||"{}");};
const isAdmin=req=>Boolean(config.adminSessionSecret)&&Boolean(verifyAdminSession(bearer(req),config.adminSessionSecret));
const defaultNotifications={telegram:true,whatsapp:false,mobile:false,email:false,quietHoursEnabled:true,quietHoursStart:"22:00",quietHoursEnd:"07:00",timezone:"Asia/Kolkata",minimumUrgency:"normal",digestEnabled:true,breakingOnly:false};
const notificationPreferences=input=>{const x=input||{};return {...defaultNotifications,telegram:Boolean(x.telegram),whatsapp:Boolean(x.whatsapp),mobile:Boolean(x.mobile),email:Boolean(x.email),whatsappNumber:String(x.whatsappNumber||"").trim()||undefined,mobileToken:String(x.mobileToken||"").trim()||undefined,quietHoursEnabled:x.quietHoursEnabled!==false,quietHoursStart:String(x.quietHoursStart||"22:00"),quietHoursEnd:String(x.quietHoursEnd||"07:00"),timezone:String(x.timezone||"Asia/Kolkata"),minimumUrgency:["low","normal","high","critical"].includes(x.minimumUrgency)?x.minimumUrgency:"normal",digestEnabled:x.digestEnabled!==false,breakingOnly:Boolean(x.breakingOnly)};};
const channelStatus=user=>({telegram:{configured:Boolean(config.telegramToken),connected:Boolean(user?.telegramChatId)},whatsapp:{configured:Boolean(config.twilioAccountSid&&config.twilioAuthToken&&config.twilioWhatsAppFrom),connected:Boolean(user?.notificationPreferences?.whatsappNumber)},mobile:{configured:Boolean(config.fcmServerKey),connected:Boolean(user?.notificationPreferences?.mobileToken)},email:{configured:false,connected:Boolean(user?.email)}});
const retry=async(fn,attempts=3)=>{let error;for(let i=0;i<attempts;i++)try{return await fn();}catch(e){error=e;if(i<attempts-1)await new Promise(r=>setTimeout(r,250*2**i));}throw error;};
async function getLatest(){let latest=null;try{latest=await latestBulletin();}catch{}if(!latest?.stories?.length){const runs=await listRuns();const local=runs.find(x=>x.status==="complete"&&x.publication?.audioUrl===latest?.audioUrl)||runs.find(x=>x.status==="complete"&&x.publication?.audioUrl);if(local){const rundown=local.steps?.find(x=>x.agent==="Editor")?.output||[];const { buildTopStories }=await import("./bulletin-feed.js");latest={...(latest||{}),headline:latest?.headline||local.publication.headline,script:latest?.script||local.publication.text,audioUrl:latest?.audioUrl||local.publication.audioUrl,sourceUrls:latest?.sourceUrls?.length?latest.sourceUrls:rundown.map(x=>x.url).filter(Boolean),stories:buildTopStories(rundown)};}}return latest;}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url,`http://${req.headers.host}`);
if(u.pathname==="/api/health")return json(res,200,{ok:true,mode:config.demoMode?"demo":"live",agents:6});
if(u.pathname==="/api/personas")return json(res,200,{personas:PERSONAS,groups:groupPersonas(PERSONAS),roles:ROLE_OPTIONS,watch:{targetTypes:TARGET_TYPES,eventTypes:EVENT_TYPES,urgencies:URGENCY}});
if(u.pathname==="/api/admin/login"&&req.method==="POST"){const x=await body(req),validUser=String(x.username||"")===config.adminUsername,validPassword=verifyPassword(String(x.password||""),config.adminPasswordHash);if(!validUser||!validPassword)return json(res,401,{error:"Invalid username or password"});return json(res,200,{token:createAdminSession(config.adminUsername,config.adminSessionSecret),username:config.adminUsername,expiresIn:28800});}
if(u.pathname==="/api/admin/session"&&req.method==="GET")return isAdmin(req)?json(res,200,{authenticated:true,username:config.adminUsername}):json(res,401,{authenticated:false});
if(u.pathname==="/api/user/login"&&req.method==="POST"){const x=await body(req),user=await retry(()=>convexUserByEmail(x.email));if(!user||!verifyUserPassword(String(x.password||""),user.passwordHash))return json(res,401,{error:"Invalid email or password"});return json(res,200,{token:createUserSession(user._id,config.userSessionSecret),userId:user._id,name:user.name});}
if(u.pathname==="/api/user/settings"&&req.method==="GET"){const userId=userFromRequest(req,config.userSessionSecret);if(!userId)return json(res,401,{error:"Sign in required"});const [user,rules,alerts]=await Promise.all([retry(()=>convexUserById(userId)),retry(()=>convexUserWatchRules(userId)),retry(()=>convexRecentWatchAlerts(userId))]);if(!user)return json(res,404,{error:"Profile not found"});return json(res,200,{user:{...user,notificationPreferences:notificationPreferences(user.notificationPreferences)},rules,alerts,channels:channelStatus(user),personas:PERSONAS});}
if(u.pathname==="/api/user/settings"&&req.method==="POST"){const userId=userFromRequest(req,config.userSessionSecret);if(!userId)return json(res,401,{error:"Sign in required"});const x=await body(req),profile=normalizeProfile(x),notification=notificationPreferences(x.notificationPreferences);if(!x.name||!profile.personas.length||!x.topics?.length)return json(res,400,{error:"Name, one persona and one news beat are required"});const user=await convexUpdateUserProfile({userId,name:String(x.name).trim(),topics:x.topics,frequency:x.frequency||"morning",personas:profile.personas,primaryPersona:profile.primaryPersona,jobTitle:profile.jobTitle||undefined,seniority:profile.seniority||undefined,geographies:profile.geographies,watchlist:profile.watchlist,insightGoals:profile.insightGoals,notificationPreferences:notification});return json(res,200,{ok:true,user,channels:channelStatus(user)});}
if(u.pathname==="/api/signup"&&req.method==="POST"){const input=await body(req);if(!input.email||!input.name||String(input.password||"").length<8||!Array.isArray(input.topics)||!input.topics.length||!input.personas?.length)return json(res,400,{error:"Name, email, password (8+ characters), one persona and one topic are required"});const profile=normalizeProfile(input);const role=input.email.trim().toLowerCase()===config.defaultAdminEmail?"admin":"user";const {password,...safeInput}=input,payload={...safeInput,...profile,passwordHash:hashUserPassword(password),role,notificationPreferences:notificationPreferences(input.notificationPreferences)};let user,storage="convex";try{user=await convexSignup(payload);}catch{}if(!user){user=await signup(payload);storage="fallback";}const token=createUserSession(user.id,config.userSessionSecret),firstBriefing=buildFirstBriefing(user,await getLatest());return json(res,200,{user,storage,token,firstBriefing,botUrl:`https://t.me/${config.telegramBotUsername}?start=${createConnectToken(user.id)}`,channelUrl:config.publicChannelUrl});}
if(u.pathname==="/api/user/instant-briefing"&&req.method==="POST"){const userId=userFromRequest(req,config.userSessionSecret);if(!userId)return json(res,401,{error:"Sign in required"});let user=null;try{user=await retry(()=>convexUserById(userId));}catch{}if(!user)user=(await listUsers()).find(x=>x.id===userId);if(!user)return json(res,404,{error:"Profile not found"});let edition=await getLatest();if(!edition?.stories?.length){const run=await runPipeline();if(run.status==="complete")edition=await getLatest();}const briefing=buildFirstBriefing(user,edition);let delivery={sent:false,reason:"telegram-not-connected"};if(user.telegramChatId&&config.telegramToken){const origin=`${req.headers["x-forwarded-proto"]||"http"}://${req.headers.host}`;const audioUrl=edition?.audioUrl?new URL(edition.audioUrl,origin).href:null;delivery=await sendTelegramBriefing(config.telegramToken,user.telegramChatId,briefing,audioUrl);}return json(res,200,{briefing,delivery,telegramConnected:Boolean(user.telegramChatId)});}
if(u.pathname==="/api/watch-rules"&&req.method==="POST"){const input=await body(req),sessionUser=userFromRequest(req,config.userSessionSecret),userId=sessionUser||input.userId,rule=normalizeWatchRule(input);if(!userId||!rule.target)return json(res,400,{error:"User and watch target are required"});const ruleId=await convexCreateWatchRule({userId,targetType:rule.targetType,target:rule.target,eventTypes:rule.eventTypes,urgency:rule.urgency});return json(res,200,{ruleId,rule});}
if(u.pathname==="/api/user/watch-toggle"&&req.method==="POST"){const userId=userFromRequest(req,config.userSessionSecret);if(!userId)return json(res,401,{error:"Sign in required"});const x=await body(req),owned=(await convexUserWatchRules(userId)).some(r=>r._id===x.ruleId);if(!owned)return json(res,403,{error:"Rule does not belong to this user"});await convexSetWatchEnabled(x.ruleId,Boolean(x.enabled));return json(res,200,{ok:true});}
if(u.pathname==="/api/user/watch-remove"&&req.method==="POST"){const userId=userFromRequest(req,config.userSessionSecret);if(!userId)return json(res,401,{error:"Sign in required"});const x=await body(req),owned=(await convexUserWatchRules(userId)).some(r=>r._id===x.ruleId);if(!owned)return json(res,403,{error:"Rule does not belong to this user"});await convexRemoveWatchRule(x.ruleId);return json(res,200,{ok:true});}
if(u.pathname==="/api/watch-rules"&&req.method==="GET"){const userId=u.searchParams.get("userId");if(!userId)return json(res,400,{error:"userId required"});return json(res,200,{rules:await convexUserWatchRules(userId)});}
if(u.pathname==="/api/admin/watch-rules"&&req.method==="GET"){if(!isAdmin(req))return json(res,401,{error:"Admin token required"});return json(res,200,{rules:await convexAllWatchRules(),alerts:await convexRecentWatchAlerts()});}
if(u.pathname==="/api/admin/watch-toggle"&&req.method==="POST"){if(!isAdmin(req))return json(res,401,{error:"Admin token required"});const x=await body(req);await convexSetWatchEnabled(x.ruleId,Boolean(x.enabled));return json(res,200,{ok:true});}
if(u.pathname==="/api/admin/watch-remove"&&req.method==="POST"){if(!isAdmin(req))return json(res,401,{error:"Admin token required"});const x=await body(req);await convexRemoveWatchRule(x.ruleId);return json(res,200,{ok:true});}
if(u.pathname==="/api/intelligence/search"&&req.method==="POST"){const input=await body(req),profile=normalizeProfile(input),plan=personaSearchPlan(profile.personas,profile.watchlist);if(!plan.queries.length)return json(res,400,{error:"Choose a supported professional persona"});if(!config.linkupKey)return json(res,503,{error:"Professional search is not configured"});const found=await searchLinkupPlan(config.linkupKey,plan),ranked=rankStoriesForProfile(found,profile).slice(0,20);let stories=attachProfessionalInsights(ranked,profile);if(config.openaiKey&&stories.length){try{const result=await generateOpenAI(config.openaiKey,config.openaiModel,"You are a professional intelligence analyst. Return JSON with an insights array matching the supplied stories in order. Each object must contain event, evidence, impact, risk, opportunity, watchpoints (array), source and sourceUrl. Use ONLY supplied story facts. For doctors emphasize clinical evidence/guidelines/safety; for bankers emphasize financials, filings, corporate actions, M&A, management changes and valuation implications. Clearly distinguish evidence from analysis. Never give personalized medical or investment advice and never invent numbers.",{profile,stories:ranked});if(validateProfessionalInsights(result.insights))stories=ranked.map((s,i)=>({...s,professionalInsight:result.insights[i]}));}catch{}}return json(res,200,{plan:{queryCount:plan.queries.length,domains:plan.domains},profile,stories});}
if(u.pathname==="/api/latest"&&req.method==="GET"){const latest=await getLatest();const personas=u.searchParams.get("personas")?.split(",").filter(Boolean)||[];const watchlist=u.searchParams.get("watchlist")?.split(",").filter(Boolean)||[];if(personas.length&&latest?.stories)latest.stories=rankStoriesForProfile(latest.stories,{personas,primaryPersona:personas[0],watchlist}).slice(0,5);return json(res,200,latest);}
if(u.pathname==="/api/runs"&&req.method==="GET")return json(res,200,await listRuns());
if(u.pathname==="/api/run"&&req.method==="POST")return json(res,200,await runPipeline());
if(u.pathname==="/api/admin/overview"&&req.method==="GET"){if(!isAdmin(req))return json(res,401,{error:"Admin token required"});const [users,runs,latest,settings]=await Promise.all([convexListUsers(),listRuns(),getLatest(),convexGetSetting("newsroom")]);return json(res,200,{users,runs:runs.slice(0,20),latest,settings:settings?.value||{pipelineEnabled:true,publicPublishing:true,defaultFrequency:"morning"},defaultAdminEmail:config.defaultAdminEmail});}
if(u.pathname==="/api/admin/user-role"&&req.method==="POST"){if(!isAdmin(req))return json(res,401,{error:"Admin token required"});const x=await body(req);if(!ROLE_OPTIONS.some(r=>r.id===x.role))return json(res,400,{error:"Invalid role"});await convexSetUserRole(x.userId,x.role);return json(res,200,{ok:true});}
if(u.pathname==="/api/admin/settings"&&req.method==="POST"){if(!isAdmin(req))return json(res,401,{error:"Admin token required"});const value=await body(req);await convexSetSetting("newsroom",value);return json(res,200,{ok:true,value});}
let p=u.pathname==="/"?"index.html":u.pathname.slice(1);p=path.join(process.cwd(),"public",p);const page=await readFile(p);res.writeHead(200,{"content-type":contentTypeFor(p),"accept-ranges":path.extname(p)===".mp3"?"bytes":"none","cache-control":path.extname(p)===".mp3"?"public, max-age=3600":"no-cache"});res.end(page);}catch(e){if(e.code==="ENOENT")return json(res,404,{error:"Not found"});json(res,500,{error:e.message});}});
server.listen(config.port,()=>console.log(`BulletNews running at http://localhost:${config.port}`));
